export type PublicProfile = {
  user_id: string;
  nome?: string | null;
  bio?: string | null;
  avatar_url?: string | null;
  country?: string | null;
  website?: string | null;
  social_links?: Record<string, unknown> | null;
  idioma?: string | null;
  account_type?: string | null;
  full_name?: string | null;
  display_name?: string | null;
  username?: string | null;
  public_bio?: string | null;
  province?: string | null;
  city?: string | null;
  preferred_language?: string | null;
  profile_visibility?: string | null;
  company_name?: string | null;
  company_category?: string | null;
  company_description?: string | null;
  company_logo_url?: string | null;
  company_website?: string | null;
  company_socials?: Record<string, unknown> | null;
  public_profile?: Record<string, unknown> | null;
  cover_url?: string | null;
  language?: string | null;
  timezone?: string | null;
  posts_count?: number | null;
  friends_count?: number | null;
  followers_count?: number | null;
  following_count?: number | null;
  stories_count?: number | null;
  is_verified?: boolean | null;
  verification_level?: string | null;
  headline?: string | null;
  profession?: string | null;
  skills?: unknown[] | null;
  interests?: unknown[] | null;
  achievements?: unknown[] | null;
  portfolio?: unknown[] | null;
  public_email?: string | null;
  contact_links?: Record<string, unknown> | null;
  reputation_level?: string | null;
  reputation_points?: number | null;
  user_level?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
};

export type PrivateProfile = {
  user_id: string;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  postal_code?: string | null;
  birth_date?: string | null;
  sex?: string | null;
  private_profile?: Record<string, unknown> | null;
  contact_preferences?: Record<string, unknown> | null;
  company_contacts?: Record<string, unknown> | null;
  associated_companies?: unknown[] | null;
  stores_created?: unknown[] | null;
  published_products?: unknown[] | null;
  offered_services?: unknown[] | null;
  company_documents?: unknown[] | null;
  consent_version?: string | null;
  consented_at?: string | null;
  two_factor_enabled?: boolean | null;
  sms_verified?: boolean | null;
  email_verified?: boolean | null;
  identity_verified?: boolean | null;
  created_at?: string | null;
  updated_at?: string | null;
};

export type SecurityProfile = {
  user_id: string;
  security_level?: string | null;
  last_login_at?: string | null;
  last_login_ip?: string | null;
  last_login_location?: string | null;
  suspicious_login_count?: number | null;
  risk_score?: number | null;
  risk_level?: string | null;
  last_security_check?: string | null;
  reputation_score?: number | null;
  successful_transactions?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
};
